# This file was generated by GoReleaser. DO NOT EDIT.
class HoneyTree < Formula
  desc "The only boilerplate project manager you ever need"
  homepage ""
  version "v0.0.1-next"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sahithyandev/honey-tree/releases/download/v0.0.1/honey-tree_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "a0cce89ca2f147aa56d83757b5f8544dabf93225cc49dee23c438459ae9a94ef"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sahithyandev/honey-tree/releases/download/v0.0.1/honey-tree_0.0.1_Linux_x86_64.tar.gz"
    sha256 "e9d2505ec3953ece38554353f2cfbabd7b132d033b49c0e13d38351167176eee"
  end

  depends_on "git"

  def install
    bin.install "honey-tree"
  end
end
